/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as WrongPortalRouteImport } from './routes/wrong-portal'
import { Route as AdminAccessRequestsRouteImport } from './routes/_admin/access-requests'
import { Route as AdminOverviewRouteImport } from './routes/_admin/overview'
import { Route as AdminTenantsRouteImport } from './routes/_admin/tenants'
import { Route as AuthResetPasswordRouteImport } from './routes/auth.reset-password'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const WrongPortalRoute = WrongPortalRouteImport.update({
  id: '/wrong-portal',
  path: '/wrong-portal',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAccessRequestsRoute = AdminAccessRequestsRouteImport.update({
  id: '/access-requests',
  path: '/access-requests',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOverviewRoute = AdminOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTenantsRoute = AdminTenantsRouteImport.update({
  id: '/tenants',
  path: '/tenants',
  getParentRoute: () => AdminRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/auth/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/wrong-portal': typeof WrongPortalRoute
  '/access-requests': typeof AdminAccessRequestsRoute
  '/overview': typeof AdminOverviewRoute
  '/tenants': typeof AdminTenantsRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/wrong-portal': typeof WrongPortalRoute
  '/access-requests': typeof AdminAccessRequestsRoute
  '/overview': typeof AdminOverviewRoute
  '/tenants': typeof AdminTenantsRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_admin': typeof AdminRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/wrong-portal': typeof WrongPortalRoute
  '/_admin/access-requests': typeof AdminAccessRequestsRoute
  '/_admin/overview': typeof AdminOverviewRoute
  '/_admin/tenants': typeof AdminTenantsRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/wrong-portal'
    | '/access-requests'
    | '/overview'
    | '/tenants'
    | '/auth/reset-password'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/wrong-portal'
    | '/access-requests'
    | '/overview'
    | '/tenants'
    | '/auth/reset-password'
  id:
    | '__root__'
    | '/'
    | '/_admin'
    | '/forgot-password'
    | '/login'
    | '/wrong-portal'
    | '/_admin/access-requests'
    | '/_admin/overview'
    | '/_admin/tenants'
    | '/auth/reset-password'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  WrongPortalRoute: typeof WrongPortalRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wrong-portal': {
      id: '/wrong-portal'
      path: '/wrong-portal'
      fullPath: '/wrong-portal'
      preLoaderRoute: typeof WrongPortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/access-requests': {
      id: '/_admin/access-requests'
      path: '/access-requests'
      fullPath: '/access-requests'
      preLoaderRoute: typeof AdminAccessRequestsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/overview': {
      id: '/_admin/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof AdminOverviewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/tenants': {
      id: '/_admin/tenants'
      path: '/tenants'
      fullPath: '/tenants'
      preLoaderRoute: typeof AdminTenantsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminAccessRequestsRoute: typeof AdminAccessRequestsRoute
  AdminOverviewRoute: typeof AdminOverviewRoute
  AdminTenantsRoute: typeof AdminTenantsRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAccessRequestsRoute: AdminAccessRequestsRoute,
  AdminOverviewRoute: AdminOverviewRoute,
  AdminTenantsRoute: AdminTenantsRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  WrongPortalRoute: WrongPortalRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
