/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/_account'
import { Route as BrowseRouteImport } from './routes/_browse'
import { Route as AccountDeletedRouteImport } from './routes/account-deleted'
import { Route as CheckEmailRouteImport } from './routes/check-email'
import { Route as CropPrototypeRouteImport } from './routes/crop-prototype'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as KitchenSinkRouteImport } from './routes/kitchen-sink'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as WrongPortalRouteImport } from './routes/wrong-portal'
import { Route as AccountApplicationsRouteImport } from './routes/_account/applications'
import { Route as AccountCvsRouteImport } from './routes/_account/cvs'
import { Route as AccountNotificationsRouteImport } from './routes/_account/notifications'
import { Route as AccountProfileRouteImport } from './routes/_account/profile'
import { Route as AccountSettingsRouteImport } from './routes/_account/settings'
import { Route as BrowseJobsRouteImport } from './routes/_browse/jobs'
import { Route as AuthConfirmRouteImport } from './routes/auth.confirm'
import { Route as AuthResetPasswordRouteImport } from './routes/auth.reset-password'
import { Route as BrowseJobsJobIdRouteImport } from './routes/_browse/jobs_.$jobId'
import { Route as BrowseLTokenRouteImport } from './routes/_browse/l.$token'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/_account',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseRoute = BrowseRouteImport.update({
  id: '/_browse',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountDeletedRoute = AccountDeletedRouteImport.update({
  id: '/account-deleted',
  path: '/account-deleted',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckEmailRoute = CheckEmailRouteImport.update({
  id: '/check-email',
  path: '/check-email',
  getParentRoute: () => rootRouteImport,
} as any)
const CropPrototypeRoute = CropPrototypeRouteImport.update({
  id: '/crop-prototype',
  path: '/crop-prototype',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const KitchenSinkRoute = KitchenSinkRouteImport.update({
  id: '/kitchen-sink',
  path: '/kitchen-sink',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const WrongPortalRoute = WrongPortalRouteImport.update({
  id: '/wrong-portal',
  path: '/wrong-portal',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountApplicationsRoute = AccountApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => AccountRoute,
} as any)
const AccountCvsRoute = AccountCvsRouteImport.update({
  id: '/cvs',
  path: '/cvs',
  getParentRoute: () => AccountRoute,
} as any)
const AccountNotificationsRoute = AccountNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AccountRoute,
} as any)
const AccountProfileRoute = AccountProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AccountRoute,
} as any)
const AccountSettingsRoute = AccountSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AccountRoute,
} as any)
const BrowseJobsRoute = BrowseJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => BrowseRoute,
} as any)
const AuthConfirmRoute = AuthConfirmRouteImport.update({
  id: '/auth/confirm',
  path: '/auth/confirm',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/auth/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseJobsJobIdRoute = BrowseJobsJobIdRouteImport.update({
  id: '/jobs_/$jobId',
  path: '/jobs/$jobId',
  getParentRoute: () => BrowseRoute,
} as any)
const BrowseLTokenRoute = BrowseLTokenRouteImport.update({
  id: '/l/$token',
  path: '/l/$token',
  getParentRoute: () => BrowseRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account-deleted': typeof AccountDeletedRoute
  '/check-email': typeof CheckEmailRoute
  '/crop-prototype': typeof CropPrototypeRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/kitchen-sink': typeof KitchenSinkRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/wrong-portal': typeof WrongPortalRoute
  '/applications': typeof AccountApplicationsRoute
  '/cvs': typeof AccountCvsRoute
  '/notifications': typeof AccountNotificationsRoute
  '/profile': typeof AccountProfileRoute
  '/settings': typeof AccountSettingsRoute
  '/jobs': typeof BrowseJobsRoute
  '/auth/confirm': typeof AuthConfirmRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/jobs/$jobId': typeof BrowseJobsJobIdRoute
  '/l/$token': typeof BrowseLTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account-deleted': typeof AccountDeletedRoute
  '/check-email': typeof CheckEmailRoute
  '/crop-prototype': typeof CropPrototypeRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/kitchen-sink': typeof KitchenSinkRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/wrong-portal': typeof WrongPortalRoute
  '/applications': typeof AccountApplicationsRoute
  '/cvs': typeof AccountCvsRoute
  '/notifications': typeof AccountNotificationsRoute
  '/profile': typeof AccountProfileRoute
  '/settings': typeof AccountSettingsRoute
  '/jobs': typeof BrowseJobsRoute
  '/auth/confirm': typeof AuthConfirmRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/jobs/$jobId': typeof BrowseJobsJobIdRoute
  '/l/$token': typeof BrowseLTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_account': typeof AccountRouteWithChildren
  '/_browse': typeof BrowseRouteWithChildren
  '/account-deleted': typeof AccountDeletedRoute
  '/check-email': typeof CheckEmailRoute
  '/crop-prototype': typeof CropPrototypeRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/kitchen-sink': typeof KitchenSinkRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/wrong-portal': typeof WrongPortalRoute
  '/_account/applications': typeof AccountApplicationsRoute
  '/_account/cvs': typeof AccountCvsRoute
  '/_account/notifications': typeof AccountNotificationsRoute
  '/_account/profile': typeof AccountProfileRoute
  '/_account/settings': typeof AccountSettingsRoute
  '/_browse/jobs': typeof BrowseJobsRoute
  '/auth/confirm': typeof AuthConfirmRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/_browse/jobs_/$jobId': typeof BrowseJobsJobIdRoute
  '/_browse/l/$token': typeof BrowseLTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account-deleted'
    | '/check-email'
    | '/crop-prototype'
    | '/forgot-password'
    | '/kitchen-sink'
    | '/login'
    | '/signup'
    | '/wrong-portal'
    | '/applications'
    | '/cvs'
    | '/notifications'
    | '/profile'
    | '/settings'
    | '/jobs'
    | '/auth/confirm'
    | '/auth/reset-password'
    | '/jobs/$jobId'
    | '/l/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account-deleted'
    | '/check-email'
    | '/crop-prototype'
    | '/forgot-password'
    | '/kitchen-sink'
    | '/login'
    | '/signup'
    | '/wrong-portal'
    | '/applications'
    | '/cvs'
    | '/notifications'
    | '/profile'
    | '/settings'
    | '/jobs'
    | '/auth/confirm'
    | '/auth/reset-password'
    | '/jobs/$jobId'
    | '/l/$token'
  id:
    | '__root__'
    | '/'
    | '/_account'
    | '/_browse'
    | '/account-deleted'
    | '/check-email'
    | '/crop-prototype'
    | '/forgot-password'
    | '/kitchen-sink'
    | '/login'
    | '/signup'
    | '/wrong-portal'
    | '/_account/applications'
    | '/_account/cvs'
    | '/_account/notifications'
    | '/_account/profile'
    | '/_account/settings'
    | '/_browse/jobs'
    | '/auth/confirm'
    | '/auth/reset-password'
    | '/_browse/jobs_/$jobId'
    | '/_browse/l/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRouteWithChildren
  BrowseRoute: typeof BrowseRouteWithChildren
  AccountDeletedRoute: typeof AccountDeletedRoute
  CheckEmailRoute: typeof CheckEmailRoute
  CropPrototypeRoute: typeof CropPrototypeRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  KitchenSinkRoute: typeof KitchenSinkRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  WrongPortalRoute: typeof WrongPortalRoute
  AuthConfirmRoute: typeof AuthConfirmRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_account': {
      id: '/_account'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_browse': {
      id: '/_browse'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof BrowseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account-deleted': {
      id: '/account-deleted'
      path: '/account-deleted'
      fullPath: '/account-deleted'
      preLoaderRoute: typeof AccountDeletedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/check-email': {
      id: '/check-email'
      path: '/check-email'
      fullPath: '/check-email'
      preLoaderRoute: typeof CheckEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crop-prototype': {
      id: '/crop-prototype'
      path: '/crop-prototype'
      fullPath: '/crop-prototype'
      preLoaderRoute: typeof CropPrototypeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kitchen-sink': {
      id: '/kitchen-sink'
      path: '/kitchen-sink'
      fullPath: '/kitchen-sink'
      preLoaderRoute: typeof KitchenSinkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wrong-portal': {
      id: '/wrong-portal'
      path: '/wrong-portal'
      fullPath: '/wrong-portal'
      preLoaderRoute: typeof WrongPortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_account/applications': {
      id: '/_account/applications'
      path: '/applications'
      fullPath: '/applications'
      preLoaderRoute: typeof AccountApplicationsRouteImport
      parentRoute: typeof AccountRoute
    }
    '/_account/cvs': {
      id: '/_account/cvs'
      path: '/cvs'
      fullPath: '/cvs'
      preLoaderRoute: typeof AccountCvsRouteImport
      parentRoute: typeof AccountRoute
    }
    '/_account/notifications': {
      id: '/_account/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AccountNotificationsRouteImport
      parentRoute: typeof AccountRoute
    }
    '/_account/profile': {
      id: '/_account/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AccountProfileRouteImport
      parentRoute: typeof AccountRoute
    }
    '/_account/settings': {
      id: '/_account/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AccountSettingsRouteImport
      parentRoute: typeof AccountRoute
    }
    '/_browse/jobs': {
      id: '/_browse/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof BrowseJobsRouteImport
      parentRoute: typeof BrowseRoute
    }
    '/auth/confirm': {
      id: '/auth/confirm'
      path: '/auth/confirm'
      fullPath: '/auth/confirm'
      preLoaderRoute: typeof AuthConfirmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_browse/jobs_/$jobId': {
      id: '/_browse/jobs_/$jobId'
      path: '/jobs/$jobId'
      fullPath: '/jobs/$jobId'
      preLoaderRoute: typeof BrowseJobsJobIdRouteImport
      parentRoute: typeof BrowseRoute
    }
    '/_browse/l/$token': {
      id: '/_browse/l/$token'
      path: '/l/$token'
      fullPath: '/l/$token'
      preLoaderRoute: typeof BrowseLTokenRouteImport
      parentRoute: typeof BrowseRoute
    }
  }
}

interface AccountRouteChildren {
  AccountApplicationsRoute: typeof AccountApplicationsRoute
  AccountCvsRoute: typeof AccountCvsRoute
  AccountNotificationsRoute: typeof AccountNotificationsRoute
  AccountProfileRoute: typeof AccountProfileRoute
  AccountSettingsRoute: typeof AccountSettingsRoute
}

const AccountRouteChildren: AccountRouteChildren = {
  AccountApplicationsRoute: AccountApplicationsRoute,
  AccountCvsRoute: AccountCvsRoute,
  AccountNotificationsRoute: AccountNotificationsRoute,
  AccountProfileRoute: AccountProfileRoute,
  AccountSettingsRoute: AccountSettingsRoute,
}

const AccountRouteWithChildren =
  AccountRoute._addFileChildren(AccountRouteChildren)

interface BrowseRouteChildren {
  BrowseJobsRoute: typeof BrowseJobsRoute
  BrowseJobsJobIdRoute: typeof BrowseJobsJobIdRoute
  BrowseLTokenRoute: typeof BrowseLTokenRoute
}

const BrowseRouteChildren: BrowseRouteChildren = {
  BrowseJobsRoute: BrowseJobsRoute,
  BrowseJobsJobIdRoute: BrowseJobsJobIdRoute,
  BrowseLTokenRoute: BrowseLTokenRoute,
}

const BrowseRouteWithChildren =
  BrowseRoute._addFileChildren(BrowseRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRouteWithChildren,
  BrowseRoute: BrowseRouteWithChildren,
  AccountDeletedRoute: AccountDeletedRoute,
  CheckEmailRoute: CheckEmailRoute,
  CropPrototypeRoute: CropPrototypeRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  KitchenSinkRoute: KitchenSinkRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  WrongPortalRoute: WrongPortalRoute,
  AuthConfirmRoute: AuthConfirmRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
