/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as DevKitchenSinkRouteImport } from './routes/dev-kitchen-sink'
import { Route as LoginRouteImport } from './routes/login'
import { Route as WrongPortalRouteImport } from './routes/wrong-portal'
import { Route as AuthedApplicationsRouteImport } from './routes/_authed.applications'
import { Route as JobsIndexRouteImport } from './routes/jobs.index'
import { Route as JobsJobIdRouteImport } from './routes/jobs.$jobId'
import { Route as LTokenRouteImport } from './routes/l.$token'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const DevKitchenSinkRoute = DevKitchenSinkRouteImport.update({
  id: '/dev-kitchen-sink',
  path: '/dev-kitchen-sink',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const WrongPortalRoute = WrongPortalRouteImport.update({
  id: '/wrong-portal',
  path: '/wrong-portal',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedApplicationsRoute = AuthedApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => AuthedRoute,
} as any)
const JobsIndexRoute = JobsIndexRouteImport.update({
  id: '/jobs/',
  path: '/jobs/',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsJobIdRoute = JobsJobIdRouteImport.update({
  id: '/jobs/$jobId',
  path: '/jobs/$jobId',
  getParentRoute: () => rootRouteImport,
} as any)
const LTokenRoute = LTokenRouteImport.update({
  id: '/l/$token',
  path: '/l/$token',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dev-kitchen-sink': typeof DevKitchenSinkRoute
  '/login': typeof LoginRoute
  '/wrong-portal': typeof WrongPortalRoute
  '/applications': typeof AuthedApplicationsRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/l/$token': typeof LTokenRoute
  '/jobs/': typeof JobsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dev-kitchen-sink': typeof DevKitchenSinkRoute
  '/login': typeof LoginRoute
  '/wrong-portal': typeof WrongPortalRoute
  '/applications': typeof AuthedApplicationsRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/l/$token': typeof LTokenRoute
  '/jobs': typeof JobsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/dev-kitchen-sink': typeof DevKitchenSinkRoute
  '/login': typeof LoginRoute
  '/wrong-portal': typeof WrongPortalRoute
  '/_authed/applications': typeof AuthedApplicationsRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/l/$token': typeof LTokenRoute
  '/jobs/': typeof JobsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dev-kitchen-sink'
    | '/login'
    | '/wrong-portal'
    | '/applications'
    | '/jobs/$jobId'
    | '/l/$token'
    | '/jobs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dev-kitchen-sink'
    | '/login'
    | '/wrong-portal'
    | '/applications'
    | '/jobs/$jobId'
    | '/l/$token'
    | '/jobs'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/dev-kitchen-sink'
    | '/login'
    | '/wrong-portal'
    | '/_authed/applications'
    | '/jobs/$jobId'
    | '/l/$token'
    | '/jobs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  DevKitchenSinkRoute: typeof DevKitchenSinkRoute
  LoginRoute: typeof LoginRoute
  WrongPortalRoute: typeof WrongPortalRoute
  JobsJobIdRoute: typeof JobsJobIdRoute
  LTokenRoute: typeof LTokenRoute
  JobsIndexRoute: typeof JobsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev-kitchen-sink': {
      id: '/dev-kitchen-sink'
      path: '/dev-kitchen-sink'
      fullPath: '/dev-kitchen-sink'
      preLoaderRoute: typeof DevKitchenSinkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wrong-portal': {
      id: '/wrong-portal'
      path: '/wrong-portal'
      fullPath: '/wrong-portal'
      preLoaderRoute: typeof WrongPortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/applications': {
      id: '/_authed/applications'
      path: '/applications'
      fullPath: '/applications'
      preLoaderRoute: typeof AuthedApplicationsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/jobs/': {
      id: '/jobs/'
      path: '/jobs'
      fullPath: '/jobs/'
      preLoaderRoute: typeof JobsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/$jobId': {
      id: '/jobs/$jobId'
      path: '/jobs/$jobId'
      fullPath: '/jobs/$jobId'
      preLoaderRoute: typeof JobsJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/l/$token': {
      id: '/l/$token'
      path: '/l/$token'
      fullPath: '/l/$token'
      preLoaderRoute: typeof LTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthedRouteChildren {
  AuthedApplicationsRoute: typeof AuthedApplicationsRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedApplicationsRoute: AuthedApplicationsRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  DevKitchenSinkRoute: DevKitchenSinkRoute,
  LoginRoute: LoginRoute,
  WrongPortalRoute: WrongPortalRoute,
  JobsJobIdRoute: JobsJobIdRoute,
  LTokenRoute: LTokenRoute,
  JobsIndexRoute: JobsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
