/**
 * PLACEHOLDER — regenerated by `pnpm gen:db-types`.
 *
 * Run a local Supabase (`supabase start`) or link a project, then:
 *   pnpm gen:db-types
 * See: https://supabase.com/docs/guides/api/rest/generating-types
 */

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export interface Database {
  public: {
    Tables: Record<string, never>;
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
}
