/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkspaceRouteImport } from './routes/_workspace'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as KitchenSinkRouteImport } from './routes/kitchen-sink'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RequestAccessRouteImport } from './routes/request-access'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as WrongPortalRouteImport } from './routes/wrong-portal'
import { Route as WorkspaceApplicationsRouteImport } from './routes/_workspace/applications'
import { Route as WorkspaceCandidatesRouteImport } from './routes/_workspace/candidates'
import { Route as WorkspaceDashboardRouteImport } from './routes/_workspace/dashboard'
import { Route as WorkspaceJobsRouteImport } from './routes/_workspace/jobs'
import { Route as WorkspaceSettingsRouteImport } from './routes/_workspace/settings'
import { Route as WorkspaceTalentPoolRouteImport } from './routes/_workspace/talent-pool'
import { Route as WorkspaceTemplatesRouteImport } from './routes/_workspace/templates'
import { Route as AuthAcceptInviteRouteImport } from './routes/auth.accept-invite'
import { Route as AuthConfirmRouteImport } from './routes/auth.confirm'
import { Route as AuthResetPasswordRouteImport } from './routes/auth.reset-password'
import { Route as WorkspaceApplicationsApplicationIdRouteImport } from './routes/_workspace/applications_.$applicationId'
import { Route as WorkspaceCandidatesCandidateIdRouteImport } from './routes/_workspace/candidates_.$candidateId'
import { Route as WorkspaceJobsJobIdRouteImport } from './routes/_workspace/jobs_.$jobId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceRoute = WorkspaceRouteImport.update({
  id: '/_workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const KitchenSinkRoute = KitchenSinkRouteImport.update({
  id: '/kitchen-sink',
  path: '/kitchen-sink',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestAccessRoute = RequestAccessRouteImport.update({
  id: '/request-access',
  path: '/request-access',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const WrongPortalRoute = WrongPortalRouteImport.update({
  id: '/wrong-portal',
  path: '/wrong-portal',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceApplicationsRoute = WorkspaceApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceCandidatesRoute = WorkspaceCandidatesRouteImport.update({
  id: '/candidates',
  path: '/candidates',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceDashboardRoute = WorkspaceDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceJobsRoute = WorkspaceJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceSettingsRoute = WorkspaceSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceTalentPoolRoute = WorkspaceTalentPoolRouteImport.update({
  id: '/talent-pool',
  path: '/talent-pool',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceTemplatesRoute = WorkspaceTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => WorkspaceRoute,
} as any)
const AuthAcceptInviteRoute = AuthAcceptInviteRouteImport.update({
  id: '/auth/accept-invite',
  path: '/auth/accept-invite',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthConfirmRoute = AuthConfirmRouteImport.update({
  id: '/auth/confirm',
  path: '/auth/confirm',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/auth/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceApplicationsApplicationIdRoute =
  WorkspaceApplicationsApplicationIdRouteImport.update({
    id: '/applications_/$applicationId',
    path: '/applications/$applicationId',
    getParentRoute: () => WorkspaceRoute,
  } as any)
const WorkspaceCandidatesCandidateIdRoute =
  WorkspaceCandidatesCandidateIdRouteImport.update({
    id: '/candidates_/$candidateId',
    path: '/candidates/$candidateId',
    getParentRoute: () => WorkspaceRoute,
  } as any)
const WorkspaceJobsJobIdRoute = WorkspaceJobsJobIdRouteImport.update({
  id: '/jobs_/$jobId',
  path: '/jobs/$jobId',
  getParentRoute: () => WorkspaceRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/kitchen-sink': typeof KitchenSinkRoute
  '/login': typeof LoginRoute
  '/request-access': typeof RequestAccessRoute
  '/signup': typeof SignupRoute
  '/wrong-portal': typeof WrongPortalRoute
  '/applications': typeof WorkspaceApplicationsRoute
  '/candidates': typeof WorkspaceCandidatesRoute
  '/dashboard': typeof WorkspaceDashboardRoute
  '/jobs': typeof WorkspaceJobsRoute
  '/settings': typeof WorkspaceSettingsRoute
  '/talent-pool': typeof WorkspaceTalentPoolRoute
  '/templates': typeof WorkspaceTemplatesRoute
  '/auth/accept-invite': typeof AuthAcceptInviteRoute
  '/auth/confirm': typeof AuthConfirmRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/applications/$applicationId': typeof WorkspaceApplicationsApplicationIdRoute
  '/candidates/$candidateId': typeof WorkspaceCandidatesCandidateIdRoute
  '/jobs/$jobId': typeof WorkspaceJobsJobIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/kitchen-sink': typeof KitchenSinkRoute
  '/login': typeof LoginRoute
  '/request-access': typeof RequestAccessRoute
  '/signup': typeof SignupRoute
  '/wrong-portal': typeof WrongPortalRoute
  '/applications': typeof WorkspaceApplicationsRoute
  '/candidates': typeof WorkspaceCandidatesRoute
  '/dashboard': typeof WorkspaceDashboardRoute
  '/jobs': typeof WorkspaceJobsRoute
  '/settings': typeof WorkspaceSettingsRoute
  '/talent-pool': typeof WorkspaceTalentPoolRoute
  '/templates': typeof WorkspaceTemplatesRoute
  '/auth/accept-invite': typeof AuthAcceptInviteRoute
  '/auth/confirm': typeof AuthConfirmRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/applications/$applicationId': typeof WorkspaceApplicationsApplicationIdRoute
  '/candidates/$candidateId': typeof WorkspaceCandidatesCandidateIdRoute
  '/jobs/$jobId': typeof WorkspaceJobsJobIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_workspace': typeof WorkspaceRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/kitchen-sink': typeof KitchenSinkRoute
  '/login': typeof LoginRoute
  '/request-access': typeof RequestAccessRoute
  '/signup': typeof SignupRoute
  '/wrong-portal': typeof WrongPortalRoute
  '/_workspace/applications': typeof WorkspaceApplicationsRoute
  '/_workspace/candidates': typeof WorkspaceCandidatesRoute
  '/_workspace/dashboard': typeof WorkspaceDashboardRoute
  '/_workspace/jobs': typeof WorkspaceJobsRoute
  '/_workspace/settings': typeof WorkspaceSettingsRoute
  '/_workspace/talent-pool': typeof WorkspaceTalentPoolRoute
  '/_workspace/templates': typeof WorkspaceTemplatesRoute
  '/auth/accept-invite': typeof AuthAcceptInviteRoute
  '/auth/confirm': typeof AuthConfirmRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/_workspace/applications_/$applicationId': typeof WorkspaceApplicationsApplicationIdRoute
  '/_workspace/candidates_/$candidateId': typeof WorkspaceCandidatesCandidateIdRoute
  '/_workspace/jobs_/$jobId': typeof WorkspaceJobsJobIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/kitchen-sink'
    | '/login'
    | '/request-access'
    | '/signup'
    | '/wrong-portal'
    | '/applications'
    | '/candidates'
    | '/dashboard'
    | '/jobs'
    | '/settings'
    | '/talent-pool'
    | '/templates'
    | '/auth/accept-invite'
    | '/auth/confirm'
    | '/auth/reset-password'
    | '/applications/$applicationId'
    | '/candidates/$candidateId'
    | '/jobs/$jobId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/kitchen-sink'
    | '/login'
    | '/request-access'
    | '/signup'
    | '/wrong-portal'
    | '/applications'
    | '/candidates'
    | '/dashboard'
    | '/jobs'
    | '/settings'
    | '/talent-pool'
    | '/templates'
    | '/auth/accept-invite'
    | '/auth/confirm'
    | '/auth/reset-password'
    | '/applications/$applicationId'
    | '/candidates/$candidateId'
    | '/jobs/$jobId'
  id:
    | '__root__'
    | '/'
    | '/_workspace'
    | '/forgot-password'
    | '/kitchen-sink'
    | '/login'
    | '/request-access'
    | '/signup'
    | '/wrong-portal'
    | '/_workspace/applications'
    | '/_workspace/candidates'
    | '/_workspace/dashboard'
    | '/_workspace/jobs'
    | '/_workspace/settings'
    | '/_workspace/talent-pool'
    | '/_workspace/templates'
    | '/auth/accept-invite'
    | '/auth/confirm'
    | '/auth/reset-password'
    | '/_workspace/applications_/$applicationId'
    | '/_workspace/candidates_/$candidateId'
    | '/_workspace/jobs_/$jobId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WorkspaceRoute: typeof WorkspaceRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  KitchenSinkRoute: typeof KitchenSinkRoute
  LoginRoute: typeof LoginRoute
  RequestAccessRoute: typeof RequestAccessRoute
  SignupRoute: typeof SignupRoute
  WrongPortalRoute: typeof WrongPortalRoute
  AuthAcceptInviteRoute: typeof AuthAcceptInviteRoute
  AuthConfirmRoute: typeof AuthConfirmRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_workspace': {
      id: '/_workspace'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof WorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kitchen-sink': {
      id: '/kitchen-sink'
      path: '/kitchen-sink'
      fullPath: '/kitchen-sink'
      preLoaderRoute: typeof KitchenSinkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/request-access': {
      id: '/request-access'
      path: '/request-access'
      fullPath: '/request-access'
      preLoaderRoute: typeof RequestAccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wrong-portal': {
      id: '/wrong-portal'
      path: '/wrong-portal'
      fullPath: '/wrong-portal'
      preLoaderRoute: typeof WrongPortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_workspace/applications': {
      id: '/_workspace/applications'
      path: '/applications'
      fullPath: '/applications'
      preLoaderRoute: typeof WorkspaceApplicationsRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/candidates': {
      id: '/_workspace/candidates'
      path: '/candidates'
      fullPath: '/candidates'
      preLoaderRoute: typeof WorkspaceCandidatesRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/dashboard': {
      id: '/_workspace/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof WorkspaceDashboardRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/jobs': {
      id: '/_workspace/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof WorkspaceJobsRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/settings': {
      id: '/_workspace/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof WorkspaceSettingsRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/talent-pool': {
      id: '/_workspace/talent-pool'
      path: '/talent-pool'
      fullPath: '/talent-pool'
      preLoaderRoute: typeof WorkspaceTalentPoolRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/templates': {
      id: '/_workspace/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof WorkspaceTemplatesRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/auth/accept-invite': {
      id: '/auth/accept-invite'
      path: '/auth/accept-invite'
      fullPath: '/auth/accept-invite'
      preLoaderRoute: typeof AuthAcceptInviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/confirm': {
      id: '/auth/confirm'
      path: '/auth/confirm'
      fullPath: '/auth/confirm'
      preLoaderRoute: typeof AuthConfirmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_workspace/applications_/$applicationId': {
      id: '/_workspace/applications_/$applicationId'
      path: '/applications/$applicationId'
      fullPath: '/applications/$applicationId'
      preLoaderRoute: typeof WorkspaceApplicationsApplicationIdRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/candidates_/$candidateId': {
      id: '/_workspace/candidates_/$candidateId'
      path: '/candidates/$candidateId'
      fullPath: '/candidates/$candidateId'
      preLoaderRoute: typeof WorkspaceCandidatesCandidateIdRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/jobs_/$jobId': {
      id: '/_workspace/jobs_/$jobId'
      path: '/jobs/$jobId'
      fullPath: '/jobs/$jobId'
      preLoaderRoute: typeof WorkspaceJobsJobIdRouteImport
      parentRoute: typeof WorkspaceRoute
    }
  }
}

interface WorkspaceRouteChildren {
  WorkspaceApplicationsRoute: typeof WorkspaceApplicationsRoute
  WorkspaceCandidatesRoute: typeof WorkspaceCandidatesRoute
  WorkspaceDashboardRoute: typeof WorkspaceDashboardRoute
  WorkspaceJobsRoute: typeof WorkspaceJobsRoute
  WorkspaceSettingsRoute: typeof WorkspaceSettingsRoute
  WorkspaceTalentPoolRoute: typeof WorkspaceTalentPoolRoute
  WorkspaceTemplatesRoute: typeof WorkspaceTemplatesRoute
  WorkspaceApplicationsApplicationIdRoute: typeof WorkspaceApplicationsApplicationIdRoute
  WorkspaceCandidatesCandidateIdRoute: typeof WorkspaceCandidatesCandidateIdRoute
  WorkspaceJobsJobIdRoute: typeof WorkspaceJobsJobIdRoute
}

const WorkspaceRouteChildren: WorkspaceRouteChildren = {
  WorkspaceApplicationsRoute: WorkspaceApplicationsRoute,
  WorkspaceCandidatesRoute: WorkspaceCandidatesRoute,
  WorkspaceDashboardRoute: WorkspaceDashboardRoute,
  WorkspaceJobsRoute: WorkspaceJobsRoute,
  WorkspaceSettingsRoute: WorkspaceSettingsRoute,
  WorkspaceTalentPoolRoute: WorkspaceTalentPoolRoute,
  WorkspaceTemplatesRoute: WorkspaceTemplatesRoute,
  WorkspaceApplicationsApplicationIdRoute:
    WorkspaceApplicationsApplicationIdRoute,
  WorkspaceCandidatesCandidateIdRoute: WorkspaceCandidatesCandidateIdRoute,
  WorkspaceJobsJobIdRoute: WorkspaceJobsJobIdRoute,
}

const WorkspaceRouteWithChildren = WorkspaceRoute._addFileChildren(
  WorkspaceRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WorkspaceRoute: WorkspaceRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  KitchenSinkRoute: KitchenSinkRoute,
  LoginRoute: LoginRoute,
  RequestAccessRoute: RequestAccessRoute,
  SignupRoute: SignupRoute,
  WrongPortalRoute: WrongPortalRoute,
  AuthAcceptInviteRoute: AuthAcceptInviteRoute,
  AuthConfirmRoute: AuthConfirmRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
