/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkspaceRouteImport } from './routes/_workspace'
import { Route as KitchenSinkRouteImport } from './routes/kitchen-sink'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as WrongPortalRouteImport } from './routes/wrong-portal'
import { Route as WorkspaceApplicationsRouteImport } from './routes/_workspace/applications'
import { Route as WorkspaceCandidatesRouteImport } from './routes/_workspace/candidates'
import { Route as WorkspaceDashboardRouteImport } from './routes/_workspace/dashboard'
import { Route as WorkspaceJobsRouteImport } from './routes/_workspace/jobs'
import { Route as WorkspaceSettingsRouteImport } from './routes/_workspace/settings'
import { Route as WorkspaceTalentPoolRouteImport } from './routes/_workspace/talent-pool'
import { Route as WorkspaceTemplatesRouteImport } from './routes/_workspace/templates'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceRoute = WorkspaceRouteImport.update({
  id: '/_workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const KitchenSinkRoute = KitchenSinkRouteImport.update({
  id: '/kitchen-sink',
  path: '/kitchen-sink',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const WrongPortalRoute = WrongPortalRouteImport.update({
  id: '/wrong-portal',
  path: '/wrong-portal',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceApplicationsRoute = WorkspaceApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceCandidatesRoute = WorkspaceCandidatesRouteImport.update({
  id: '/candidates',
  path: '/candidates',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceDashboardRoute = WorkspaceDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceJobsRoute = WorkspaceJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceSettingsRoute = WorkspaceSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceTalentPoolRoute = WorkspaceTalentPoolRouteImport.update({
  id: '/talent-pool',
  path: '/talent-pool',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceTemplatesRoute = WorkspaceTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => WorkspaceRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/kitchen-sink': typeof KitchenSinkRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/wrong-portal': typeof WrongPortalRoute
  '/applications': typeof WorkspaceApplicationsRoute
  '/candidates': typeof WorkspaceCandidatesRoute
  '/dashboard': typeof WorkspaceDashboardRoute
  '/jobs': typeof WorkspaceJobsRoute
  '/settings': typeof WorkspaceSettingsRoute
  '/talent-pool': typeof WorkspaceTalentPoolRoute
  '/templates': typeof WorkspaceTemplatesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/kitchen-sink': typeof KitchenSinkRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/wrong-portal': typeof WrongPortalRoute
  '/applications': typeof WorkspaceApplicationsRoute
  '/candidates': typeof WorkspaceCandidatesRoute
  '/dashboard': typeof WorkspaceDashboardRoute
  '/jobs': typeof WorkspaceJobsRoute
  '/settings': typeof WorkspaceSettingsRoute
  '/talent-pool': typeof WorkspaceTalentPoolRoute
  '/templates': typeof WorkspaceTemplatesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_workspace': typeof WorkspaceRouteWithChildren
  '/kitchen-sink': typeof KitchenSinkRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/wrong-portal': typeof WrongPortalRoute
  '/_workspace/applications': typeof WorkspaceApplicationsRoute
  '/_workspace/candidates': typeof WorkspaceCandidatesRoute
  '/_workspace/dashboard': typeof WorkspaceDashboardRoute
  '/_workspace/jobs': typeof WorkspaceJobsRoute
  '/_workspace/settings': typeof WorkspaceSettingsRoute
  '/_workspace/talent-pool': typeof WorkspaceTalentPoolRoute
  '/_workspace/templates': typeof WorkspaceTemplatesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/kitchen-sink'
    | '/login'
    | '/signup'
    | '/wrong-portal'
    | '/applications'
    | '/candidates'
    | '/dashboard'
    | '/jobs'
    | '/settings'
    | '/talent-pool'
    | '/templates'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/kitchen-sink'
    | '/login'
    | '/signup'
    | '/wrong-portal'
    | '/applications'
    | '/candidates'
    | '/dashboard'
    | '/jobs'
    | '/settings'
    | '/talent-pool'
    | '/templates'
  id:
    | '__root__'
    | '/'
    | '/_workspace'
    | '/kitchen-sink'
    | '/login'
    | '/signup'
    | '/wrong-portal'
    | '/_workspace/applications'
    | '/_workspace/candidates'
    | '/_workspace/dashboard'
    | '/_workspace/jobs'
    | '/_workspace/settings'
    | '/_workspace/talent-pool'
    | '/_workspace/templates'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WorkspaceRoute: typeof WorkspaceRouteWithChildren
  KitchenSinkRoute: typeof KitchenSinkRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  WrongPortalRoute: typeof WrongPortalRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_workspace': {
      id: '/_workspace'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof WorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kitchen-sink': {
      id: '/kitchen-sink'
      path: '/kitchen-sink'
      fullPath: '/kitchen-sink'
      preLoaderRoute: typeof KitchenSinkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wrong-portal': {
      id: '/wrong-portal'
      path: '/wrong-portal'
      fullPath: '/wrong-portal'
      preLoaderRoute: typeof WrongPortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_workspace/applications': {
      id: '/_workspace/applications'
      path: '/applications'
      fullPath: '/applications'
      preLoaderRoute: typeof WorkspaceApplicationsRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/candidates': {
      id: '/_workspace/candidates'
      path: '/candidates'
      fullPath: '/candidates'
      preLoaderRoute: typeof WorkspaceCandidatesRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/dashboard': {
      id: '/_workspace/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof WorkspaceDashboardRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/jobs': {
      id: '/_workspace/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof WorkspaceJobsRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/settings': {
      id: '/_workspace/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof WorkspaceSettingsRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/talent-pool': {
      id: '/_workspace/talent-pool'
      path: '/talent-pool'
      fullPath: '/talent-pool'
      preLoaderRoute: typeof WorkspaceTalentPoolRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/templates': {
      id: '/_workspace/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof WorkspaceTemplatesRouteImport
      parentRoute: typeof WorkspaceRoute
    }
  }
}

interface WorkspaceRouteChildren {
  WorkspaceApplicationsRoute: typeof WorkspaceApplicationsRoute
  WorkspaceCandidatesRoute: typeof WorkspaceCandidatesRoute
  WorkspaceDashboardRoute: typeof WorkspaceDashboardRoute
  WorkspaceJobsRoute: typeof WorkspaceJobsRoute
  WorkspaceSettingsRoute: typeof WorkspaceSettingsRoute
  WorkspaceTalentPoolRoute: typeof WorkspaceTalentPoolRoute
  WorkspaceTemplatesRoute: typeof WorkspaceTemplatesRoute
}

const WorkspaceRouteChildren: WorkspaceRouteChildren = {
  WorkspaceApplicationsRoute: WorkspaceApplicationsRoute,
  WorkspaceCandidatesRoute: WorkspaceCandidatesRoute,
  WorkspaceDashboardRoute: WorkspaceDashboardRoute,
  WorkspaceJobsRoute: WorkspaceJobsRoute,
  WorkspaceSettingsRoute: WorkspaceSettingsRoute,
  WorkspaceTalentPoolRoute: WorkspaceTalentPoolRoute,
  WorkspaceTemplatesRoute: WorkspaceTemplatesRoute,
}

const WorkspaceRouteWithChildren = WorkspaceRoute._addFileChildren(
  WorkspaceRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WorkspaceRoute: WorkspaceRouteWithChildren,
  KitchenSinkRoute: KitchenSinkRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  WrongPortalRoute: WrongPortalRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
