/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness check */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness check
         * @description Fails as a 500 problem+json if the database is unreachable.
         */
        get: operations["getReadiness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/signup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create a candidate account
         * @description Provision the identity, the Profile and the Candidate, and send a confirmation email.
         *
         *     No session comes back: the candidate has to confirm the address before they can sign in.
         *     Anything that fails part-way leaves the address free to sign up again.
         */
        post: operations["signUp"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/confirm-email": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Confirm an email address
         * @description Redeem the `token_hash` from the confirmation email, and sign the candidate in.
         *
         *     Signing them in is not a shortcut: redeeming the token proves they read mail sent to
         *     that address, which is the same thing a password proves about the account.
         */
        post: operations["confirmEmail"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/accept-invite": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Accept a teammate invitation
         * @description Redeem the `token_hash` from an invite email, choose a password, and sign in.
         *
         *     The Recruiter and their Tenant membership already exist — inviting is what created them
         *     — so this adds the one thing missing and drops the invitee straight into their team.
         */
        post: operations["acceptInvite"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start a session */
        post: operations["logIn"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Rotate the session
         * @description Exchange the refresh cookie for a new session, and replace both cookies with it.
         */
        post: operations["refreshSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * End the session
         * @description Revoke every session the caller has, then clear their cookies.
         *
         *     Succeeds whatever state the caller is in — a logout that could fail would be a way to
         *     leave someone signed in.
         */
        post: operations["logOut"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The signed-in Profile
         * @description Who the session cookie belongs to, once Supabase has verified its token.
         */
        get: operations["getCurrentProfile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/password-reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ask for a password-reset email
         * @description Send the reset email, if the address has an account.
         *
         *     Accepted either way, and with the same latency-free answer either way: a caller must not
         *     be able to learn from this endpoint whether an address is registered.
         */
        post: operations["requestPasswordReset"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/password-reset/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Set a new password
         * @description Redeem the `token_hash` from the reset email and set the new password.
         *
         *     Ends every session the account had, this caller's included, so the new password is the
         *     only way back in.
         */
        post: operations["confirmPasswordReset"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/tenants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create a tenant and its founding admin
         * @description Self-serve onto the platform: one call creates the Tenant and the admin who runs it.
         *
         *     No session comes back, exactly as for a candidate: the founder confirms their address
         *     first. Anything that fails part-way leaves neither a Tenant nor a usable address behind.
         */
        post: operations["signUpTenant"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/tenants/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The tenant the caller recruits for
         * @description Answers only while both kill-switches are off, which makes it the SPA's liveness check.
         */
        get: operations["getMyTenant"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/tenants/me/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The tenant's recruiters
         * @description Everyone on the roster, deactivated colleagues included — an admin has to see someone
         *     to reactivate them. Any recruiter may read it; only an admin may change it.
         */
        get: operations["listTenantMembers"];
        put?: never;
        /**
         * Invite a teammate
         * @description Mail an invitation and add the invitee to the roster in the same breath.
         *
         *     They are a member from this moment — 201 is not a promise, it is the row — but they
         *     cannot sign in until they follow the link and choose a password. An address that already
         *     belongs to anyone, Candidate or Recruiter, is refused: one address, one account.
         */
        post: operations["inviteTenantMember"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/tenants/me/members/{recruiter_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Change a teammate's role or access
         * @description Promote, demote, deactivate or reinstate a colleague.
         *
         *     Deactivating is how a departure is handled: the row and everything attached to it stays,
         *     and the person is refused at the door on their very next request.
         */
        patch: operations["changeTenantMember"];
        trace?: never;
    };
    "/v1/candidates/me/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The caller's whole professional profile
         * @description Everything the profile form renders, in one payload — and a valid body to `PUT` back.
         *
         *     Every section is present even when empty: the form is the same form either way.
         */
        get: operations["getMyProfile"];
        /**
         * Replace the caller's whole professional profile
         * @description Save the profile whole, and answer with what was stored.
         *
         *     A replacement, not a patch: a section the body leaves out is a section the candidate
         *     has emptied. The save is one transaction, so it either all happened or none of it did.
         */
        put: operations["replaceMyProfile"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/candidates/me/cvs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload a CV
         * @description Store the file and start reading it.
         *
         *     Answers as soon as the CV exists, not when it has been parsed — the reading happens in
         *     the worker and takes about ten seconds. The response comes back `uploaded`; poll the
         *     CV until it is `ready` or `failed`.
         *
         *     The same file twice is a 409 rather than a second CV, and the 409 carries the id of the
         *     CV already holding it.
         */
        post: operations["uploadMyCv"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/candidates/me/cvs/{cv_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * A CV and how far its parse has got
         * @description What to poll while a CV is being read.
         *
         *     `parsing_status` is the authoritative state: `uploaded` and `processing` mean keep
         *     waiting, `ready` means `parsed_cv` is filled in, and `failed` means it never will be
         *     and `parsing_error` says why.
         */
        get: operations["getMyCv"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/candidates/me/cvs/{cv_id}/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * A short-lived link to the original file
         * @description Where to fetch the file the candidate uploaded.
         *
         *     A fresh link each time, good for a few minutes. Ask for one when the candidate clicks;
         *     storing one is storing a key to the document.
         */
        get: operations["getMyCvDownloadLink"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AcceptInviteRequest */
        AcceptInviteRequest: {
            /**
             * Token Hash
             * @description The `token_hash` from the emailed link.
             */
            token_hash: string;
            /**
             * Password
             * @description At least 8 characters.
             * @example correct-horse-battery
             */
            password: string;
        };
        /**
         * AccountType
         * @enum {string}
         */
        AccountType: "candidate" | "recruiter";
        /** Body_uploadMyCv */
        Body_uploadMyCv: {
            /**
             * File
             * @description The CV: PDF, DOC or DOCX, up to 10 MB.
             */
            file: string;
        };
        /**
         * CandidateProfile
         * @description Everything a Candidate says about themselves professionally.
         *
         *     One model for both directions: a `GET` body is a valid `PUT` body, unchanged.
         */
        CandidateProfile: {
            /**
             * Headline
             * @example Backend engineer, 8 years
             */
            headline?: string | null;
            /** Summary */
            summary?: string | null;
            /**
             * Location
             * @example Damascus, Syria
             */
            location?: string | null;
            /** Preferred Language Code */
            preferred_language_code?: string | null;
            /**
             * Is Searchable
             * @description Opt in to cross-tenant Global search. Requires a current, ready CV.
             * @default false
             */
            is_searchable: boolean;
            /**
             * Experiences
             * @description Jobs, in the candidate's own order.
             */
            experiences?: components["schemas"]["ProfileExperience"][];
            /**
             * Educations
             * @description Qualifications, in the candidate's own order.
             */
            educations?: components["schemas"]["ProfileEducation"][];
            /**
             * Skills
             * @description Canonical skills, in the candidate's own order.
             */
            skills?: components["schemas"]["ProfileSkill"][];
            /**
             * Languages
             * @description Languages spoken, in the candidate's own order.
             */
            languages?: components["schemas"]["ProfileLanguage"][];
            /**
             * Projects
             * @description Projects, in the candidate's own order.
             */
            projects?: components["schemas"]["ProfileProject"][];
        };
        /**
         * ChangeMemberRequest
         * @description Both fields optional: an admin changing a role should not have to restate access.
         */
        ChangeMemberRequest: {
            role?: components["schemas"]["RecruiterRole"] | null;
            /** Is Active */
            is_active?: boolean | null;
        };
        /** ConfirmEmailRequest */
        ConfirmEmailRequest: {
            /**
             * Token Hash
             * @description The `token_hash` from the emailed link.
             */
            token_hash: string;
        };
        /** ConfirmPasswordResetRequest */
        ConfirmPasswordResetRequest: {
            /**
             * Token Hash
             * @description The `token_hash` from the emailed link.
             */
            token_hash: string;
            /**
             * Password
             * @description At least 8 characters.
             * @example correct-horse-battery
             */
            password: string;
        };
        /**
         * Cv
         * @description One uploaded CV, and how far the platform has got with it.
         */
        Cv: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Display Name
             * @description The name of the file the candidate uploaded.
             */
            display_name: string;
            /** @description The authoritative state of this CV. Poll until it leaves `processing`. */
            parsing_status: components["schemas"]["CvParsingStatus"];
            /**
             * Parsing Error
             * @description Why the parse failed, when it did. Null otherwise.
             */
            parsing_error?: string | null;
            /**
             * Detected Language
             * @description The language the CV is written in, once it has been read.
             */
            detected_language?: string | null;
            /**
             * Is Current
             * @description Whether this is the CV the candidate applies and is found with.
             */
            is_current: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Parsed At */
            parsed_at?: string | null;
            /** @description What the AI read out of the CV — present only once `parsing_status` is `ready`. Skills are Canonical skills; everything else the CV named is in `unmapped_skills` for the candidate to review. */
            parsed_cv?: components["schemas"]["ParsedCv"] | null;
        };
        /**
         * CvDownloadLink
         * @description Where to fetch the original file, for as long as the link lasts.
         */
        CvDownloadLink: {
            /**
             * Url
             * @description A signed URL. Anyone holding it can read the file.
             */
            url: string;
            /**
             * Expires In Seconds
             * @description How long the URL stays good for. Ask again rather than storing it.
             */
            expires_in_seconds: number;
        };
        /**
         * CvParsingStatus
         * @enum {string}
         */
        CvParsingStatus: "uploaded" | "processing" | "ready" | "failed";
        /**
         * DuplicateCvProblemDetail
         * @description A refused upload that can name the CV the candidate already has.
         *
         *     A typed member rather than a bare extension: the id is the useful half of this refusal
         *     — it is what lets the SPA go straight to that CV — and a client cannot rely on
         *     something the OpenAPI document only mentions in prose.
         */
        DuplicateCvProblemDetail: {
            /**
             * Type
             * @description Stable identifier for what went wrong.
             * @default about:blank
             * @example about:blank
             */
            type: string;
            /**
             * Title
             * @description Short, human-readable summary of the problem type.
             */
            title: string;
            /**
             * Status
             * @description The HTTP status code, repeated for out-of-band handling.
             */
            status: number;
            /**
             * Detail
             * @description Explanation specific to this occurrence.
             */
            detail?: string | null;
            /**
             * Instance
             * @description Path of the request that produced the problem.
             */
            instance?: string | null;
            /**
             * Request Id
             * @description Correlates this response with the server logs.
             */
            request_id?: string | null;
            /**
             * Cv Id
             * Format: uuid
             * @description The CV already holding this exact file.
             */
            cv_id: string;
        } & {
            [key: string]: unknown;
        };
        /**
         * Health
         * @description The process is up and serving.
         */
        Health: {
            /**
             * Status
             * @default ok
             * @constant
             */
            status: "ok";
        };
        /**
         * InvalidField
         * @description One rejected input, located by where it appeared in the request.
         */
        InvalidField: {
            /**
             * Location
             * @description Dotted path to the offending value, e.g. `body.email`.
             * @example body.email
             */
            location: string;
            /**
             * Message
             * @description Why the value was rejected.
             */
            message: string;
            /**
             * Type
             * @description Machine-readable validation rule that failed.
             */
            type: string;
        };
        /** InviteMemberRequest */
        InviteMemberRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Full Name */
            full_name: string;
            /** @default recruiter */
            role: components["schemas"]["RecruiterRole"];
        };
        /**
         * LanguageProficiency
         * @enum {string}
         */
        LanguageProficiency: "beginner" | "intermediate" | "advanced" | "fluent" | "native";
        /** LogInRequest */
        LogInRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /**
             * Password
             * @description At least 8 characters.
             * @example correct-horse-battery
             */
            password: string;
        };
        /**
         * MemberView
         * @description One Recruiter on the roster.
         */
        MemberView: {
            /**
             * Id
             * @description Shared with the Supabase Auth user and the Profile.
             */
            id: string;
            /** Full Name */
            full_name: string;
            /**
             * Email
             * Format: email
             */
            email: string;
            role: components["schemas"]["RecruiterRole"];
            /**
             * Is Active
             * @description False once an admin has revoked their access.
             */
            is_active: boolean;
        };
        /**
         * NewTenantView
         * @description What self-serve signup produced.
         */
        NewTenantView: {
            tenant: components["schemas"]["TenantView"];
            admin: components["schemas"]["MemberView"];
        };
        /**
         * ParsedCv
         * @description Everything read out of one CV.
         *
         *     Every field is present in the model's answer — the strict-schema subset has no optional
         *     properties, only nullable ones — so "the CV does not say" is `null` or an empty list
         *     throughout, never an absent key.
         */
        ParsedCv: {
            /**
             * Full Name
             * @description The candidate's name as the CV gives it.
             */
            full_name: string | null;
            /** Email */
            email: string | null;
            /** Phone */
            phone: string | null;
            /**
             * Detected Language
             * @description The language the CV itself is written in, as an ISO 639-1 code.
             */
            detected_language: string | null;
            /**
             * Headline
             * @description The one-line professional title the CV leads with, if it has one.
             * @example Backend engineer, 8 years
             */
            headline: string | null;
            /**
             * Summary
             * @description The CV's own professional summary, if it has one.
             */
            summary: string | null;
            /**
             * Location
             * @description Where the candidate is, as the CV puts it.
             */
            location: string | null;
            /**
             * Experiences
             * @description Every job, most recent first.
             */
            experiences: components["schemas"]["ParsedExperience"][];
            /**
             * Educations
             * @description Every qualification, most recent first.
             */
            educations: components["schemas"]["ParsedEducation"][];
            /**
             * Skills
             * @description Every Canonical skill the CV evidences, by its exact name.
             */
            skills: components["schemas"]["ParsedSkill"][];
            /**
             * Languages
             * @description Every language the CV claims.
             */
            languages: components["schemas"]["ParsedLanguage"][];
            /**
             * Projects
             * @description Every project the CV describes.
             */
            projects: components["schemas"]["ParsedProject"][];
            /**
             * Unmapped Skills
             * @description Every skill the CV names that is not in the Canonical list, in the CV's own words. The candidate sees these at review; they never reach Screening.
             */
            unmapped_skills: string[];
        };
        /**
         * ParsedEducation
         * @description One qualification the CV describes.
         */
        ParsedEducation: {
            /** Institution */
            institution: string;
            /** Degree */
            degree: string | null;
            /** Field Of Study */
            field_of_study: string | null;
            /** Graduation Year */
            graduation_year: number | null;
            /** Description */
            description: string | null;
        };
        /**
         * ParsedExperience
         * @description One job the CV describes.
         */
        ParsedExperience: {
            /** Job Title */
            job_title: string;
            /**
             * Company Name
             * @description Null when the CV does not name one.
             */
            company_name: string | null;
            /** Start Year */
            start_year: number | null;
            /** Start Month */
            start_month: number | null;
            /**
             * End Year
             * @description Null for a job the candidate still holds.
             */
            end_year: number | null;
            /** End Month */
            end_month: number | null;
            /**
             * Is Current
             * @description The CV presents this as the candidate's job today.
             */
            is_current: boolean;
            /**
             * Description
             * @description What the CV says they did, in its own words.
             */
            description: string | null;
        };
        /**
         * ParsedLanguage
         * @description One language the CV claims, and how well.
         */
        ParsedLanguage: {
            /**
             * Code
             * @description Exactly as spelled in the list of language codes.
             */
            code: string;
            /** @description The CV's own claim, mapped to the nearest of these. Use `fluent` for a language described as professional or business level. */
            proficiency: components["schemas"]["LanguageProficiency"];
        };
        /**
         * ParsedProject
         * @description One thing the CV says the candidate built.
         */
        ParsedProject: {
            /** Name */
            name: string;
            /** Description */
            description: string | null;
            /** Project Url */
            project_url: string | null;
            /** Repository Url */
            repository_url: string | null;
            /** Start Year */
            start_year: number | null;
            /** Start Month */
            start_month: number | null;
            /** End Year */
            end_year: number | null;
            /** End Month */
            end_month: number | null;
        };
        /**
         * ParsedSkill
         * @description One Canonical skill the CV evidences.
         *
         *     `name` must be a Canonical skill spelled exactly as the prompt listed it. The backend
         *     checks that rather than trusting it (ADR-0006): a name that is not in the taxonomy is
         *     moved to `unmapped_skills`, where it is reviewed and never reaches Screening.
         */
        ParsedSkill: {
            /**
             * Name
             * @description Exactly as spelled in the list of Canonical skills.
             */
            name: string;
            /**
             * Years Experience
             * @description Years of it, if the CV supports a figure. Null when it does not — a guess here becomes a number a recruiter filters on.
             */
            years_experience: number | null;
        };
        /** PasswordResetRequest */
        PasswordResetRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
        };
        /**
         * ProblemDetail
         * @description The body of any error response.
         */
        ProblemDetail: {
            /**
             * Type
             * @description Stable identifier for what went wrong.
             * @default about:blank
             * @example about:blank
             */
            type: string;
            /**
             * Title
             * @description Short, human-readable summary of the problem type.
             */
            title: string;
            /**
             * Status
             * @description The HTTP status code, repeated for out-of-band handling.
             */
            status: number;
            /**
             * Detail
             * @description Explanation specific to this occurrence.
             */
            detail?: string | null;
            /**
             * Instance
             * @description Path of the request that produced the problem.
             */
            instance?: string | null;
            /**
             * Request Id
             * @description Correlates this response with the server logs.
             */
            request_id?: string | null;
        } & {
            [key: string]: unknown;
        };
        /**
         * ProfileEducation
         * @description One qualification.
         */
        ProfileEducation: {
            /** Institution */
            institution: string;
            /** Degree */
            degree?: string | null;
            /** Field Of Study */
            field_of_study?: string | null;
            /** Graduation Year */
            graduation_year?: number | null;
            /** Description */
            description?: string | null;
        };
        /**
         * ProfileExperience
         * @description One job.
         */
        ProfileExperience: {
            /** Start Year */
            start_year?: number | null;
            /** Start Month */
            start_month?: number | null;
            /** End Year */
            end_year?: number | null;
            /** End Month */
            end_month?: number | null;
            /** Job Title */
            job_title: string;
            /** Company Name */
            company_name?: string | null;
            /**
             * Is Current
             * @description A job with no end, still going.
             * @default false
             */
            is_current: boolean;
            /** Description */
            description?: string | null;
        };
        /**
         * ProfileLanguage
         * @description One language the candidate speaks, and how well.
         */
        ProfileLanguage: {
            /**
             * Code
             * @description A code from the platform's `languages` table.
             * @example en
             */
            code: string;
            proficiency: components["schemas"]["LanguageProficiency"];
        };
        /**
         * ProfileProject
         * @description One thing the candidate built.
         */
        ProfileProject: {
            /** Start Year */
            start_year?: number | null;
            /** Start Month */
            start_month?: number | null;
            /** End Year */
            end_year?: number | null;
            /** End Month */
            end_month?: number | null;
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            /** Project Url */
            project_url?: string | null;
            /** Repository Url */
            repository_url?: string | null;
        };
        /**
         * ProfileSkill
         * @description One Canonical skill, and how long the candidate has been doing it.
         *
         *     Named rather than identified: a Canonical skill *is* its one spelling, and the CV parse
         *     speaks in those names — so the review flow can post back what it read.
         */
        ProfileSkill: {
            /**
             * Name
             * @description The Canonical skill's exact name.
             * @example Python
             */
            name: string;
            /**
             * Years Experience
             * @description Stored to one decimal place. Null means unstated.
             */
            years_experience?: number | null;
        };
        /**
         * ProfileView
         * @description The acting Profile, as every auth route reports it.
         */
        ProfileView: {
            /**
             * Id
             * @description Shared with the Supabase Auth user and the Candidate row.
             */
            id: string;
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Full Name */
            full_name: string;
            account_type: components["schemas"]["AccountType"];
            /** Avatar Url */
            avatar_url: string | null;
            /** Phone */
            phone: string | null;
        };
        /**
         * Readiness
         * @description The process is up and its dependencies answer.
         */
        Readiness: {
            /**
             * Status
             * @default ok
             * @constant
             */
            status: "ok";
            /**
             * Database
             * @default ok
             * @constant
             */
            database: "ok";
        };
        /**
         * RecruiterRole
         * @enum {string}
         */
        RecruiterRole: "admin" | "recruiter";
        /** SignUpRequest */
        SignUpRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /**
             * Password
             * @description At least 8 characters.
             * @example correct-horse-battery
             */
            password: string;
            /** Full Name */
            full_name: string;
        };
        /** SignUpTenantRequest */
        SignUpTenantRequest: {
            /**
             * Tenant Name
             * @description The hiring company's display name.
             */
            tenant_name: string;
            /**
             * Slug
             * @description Lowercase letters, digits and single hyphens.
             * @example acme-recruiting
             */
            slug: string;
            /**
             * Email
             * Format: email
             * @description The founding admin's address.
             */
            email: string;
            /**
             * Password
             * @description At least 8 characters.
             * @example correct-horse-battery
             */
            password: string;
            /**
             * Full Name
             * @description The founding admin's name.
             */
            full_name: string;
        };
        /**
         * TenantView
         * @description A Tenant as its own recruiters see it.
         */
        TenantView: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Slug */
            slug: string;
        };
        /**
         * ValidationProblemDetail
         * @description A problem that can name every input it rejected.
         */
        ValidationProblemDetail: {
            /**
             * Type
             * @description Stable identifier for what went wrong.
             * @default about:blank
             * @example about:blank
             */
            type: string;
            /**
             * Title
             * @description Short, human-readable summary of the problem type.
             */
            title: string;
            /**
             * Status
             * @description The HTTP status code, repeated for out-of-band handling.
             */
            status: number;
            /**
             * Detail
             * @description Explanation specific to this occurrence.
             */
            detail?: string | null;
            /**
             * Instance
             * @description Path of the request that produced the problem.
             */
            instance?: string | null;
            /**
             * Request Id
             * @description Correlates this response with the server logs.
             */
            request_id?: string | null;
            /**
             * Errors
             * @description Every field that failed validation.
             */
            errors: components["schemas"]["InvalidField"][];
        } & {
            [key: string]: unknown;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
            /** @description The request did not match the expected shape. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ValidationProblemDetail"];
                };
            };
            /** @description Something went wrong on the server. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    getReadiness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Readiness"];
                };
            };
            /** @description The request did not match the expected shape. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ValidationProblemDetail"];
                };
            };
            /** @description Something went wrong on the server. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    signUp: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SignUpRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileView"];
                };
            };
            /** @description The identity provider rejected the password. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description An account already exists for this email address. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description The request did not match the expected shape. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ValidationProblemDetail"];
                };
            };
            /** @description Something went wrong on the server. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description The identity provider is not answering. */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    confirmEmail: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfirmEmailRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileView"];
                };
            };
            /** @description The link is invalid, spent, or expired. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description The request did not match the expected shape. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ValidationProblemDetail"];
                };
            };
            /** @description Something went wrong on the server. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description The identity provider is not answering. */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    acceptInvite: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AcceptInviteRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileView"];
                };
            };
            /** @description The link is spent or expired, or the password was refused. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description The request did not match the expected shape. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ValidationProblemDetail"];
                };
            };
            /** @description Something went wrong on the server. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description The identity provider is not answering. */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    logIn: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LogInRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileView"];
                };
            };
            /** @description The email and password do not match an account. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description The email address has not been confirmed yet. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description The request did not match the expected shape. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ValidationProblemDetail"];
                };
            };
            /** @description Something went wrong on the server. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description The identity provider is not answering. */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    refreshSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileView"];
                };
            };
            /** @description The session is over — sign in again. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description The request did not match the expected shape. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ValidationProblemDetail"];
                };
            };
            /** @description Something went wrong on the server. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description The identity provider is not answering. */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    logOut: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The request did not match the expected shape. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ValidationProblemDetail"];
                };
            };
            /** @description Something went wrong on the server. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    getCurrentProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileView"];
                };
            };
            /** @description There is no valid session. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description The request did not match the expected shape. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ValidationProblemDetail"];
                };
            };
            /** @description Something went wrong on the server. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    requestPasswordReset: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordResetRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The request did not match the expected shape. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ValidationProblemDetail"];
                };
            };
            /** @description Something went wrong on the server. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description The identity provider is not answering. */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    confirmPasswordReset: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfirmPasswordResetRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The link is spent or expired, or the password was refused. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description The request did not match the expected shape. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ValidationProblemDetail"];
                };
            };
            /** @description Something went wrong on the server. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description The identity provider is not answering. */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    signUpTenant: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SignUpTenantRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NewTenantView"];
                };
            };
            /** @description The identity provider rejected the password. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description The slug or the email address is already taken. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description The request did not match the expected shape. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ValidationProblemDetail"];
                };
            };
            /** @description Something went wrong on the server. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description The identity provider is not answering. */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    getMyTenant: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TenantView"];
                };
            };
            /** @description There is no valid session. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description The caller is not a recruiter, has been deactivated, or their tenant is suspended. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description The request did not match the expected shape. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ValidationProblemDetail"];
                };
            };
            /** @description Something went wrong on the server. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    listTenantMembers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberView"][];
                };
            };
            /** @description There is no valid session. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description The caller is not a recruiter, has been deactivated, or their tenant is suspended. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description The request did not match the expected shape. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ValidationProblemDetail"];
                };
            };
            /** @description Something went wrong on the server. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    inviteTenantMember: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InviteMemberRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberView"];
                };
            };
            /** @description There is no valid session. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description The caller is not a recruiter, has been deactivated, or their tenant is suspended. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description That email address already has a Sync account. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description The request did not match the expected shape. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ValidationProblemDetail"];
                };
            };
            /** @description Something went wrong on the server. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description The identity provider is not answering. */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    changeTenantMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                recruiter_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangeMemberRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberView"];
                };
            };
            /** @description There is no valid session. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description The caller is not a recruiter, has been deactivated, or their tenant is suspended. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description No such member of this tenant. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description The change would leave the tenant with no active admin. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description The request did not match the expected shape. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ValidationProblemDetail"];
                };
            };
            /** @description Something went wrong on the server. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    getMyProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CandidateProfile"];
                };
            };
            /** @description There is no valid session. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description The caller is not a candidate. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description The request did not match the expected shape. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ValidationProblemDetail"];
                };
            };
            /** @description Something went wrong on the server. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    replaceMyProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CandidateProfile"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CandidateProfile"];
                };
            };
            /** @description There is no valid session. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description The caller is not a candidate. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Opting in to Global search needs a current CV. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description A skill is not a Canonical skill, or a language code is not one the platform knows. Both name the offending entries. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ValidationProblemDetail"];
                };
            };
            /** @description Something went wrong on the server. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    uploadMyCv: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_uploadMyCv"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Cv"];
                };
            };
            /** @description There is no valid session. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description The caller is not a candidate. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description This exact file is already one of the caller's CVs; `cv_id` is the one it is. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["DuplicateCvProblemDetail"];
                };
            };
            /** @description The file is larger than the platform accepts. */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description The file is not a PDF, DOC or DOCX. */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description The request did not match the expected shape. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ValidationProblemDetail"];
                };
            };
            /** @description Something went wrong on the server. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description The file store could not be reached. */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    getMyCv: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cv_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Cv"];
                };
            };
            /** @description There is no valid session. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description The caller is not a candidate. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description The caller has no CV with that id. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description The request did not match the expected shape. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ValidationProblemDetail"];
                };
            };
            /** @description Something went wrong on the server. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    getMyCvDownloadLink: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cv_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CvDownloadLink"];
                };
            };
            /** @description There is no valid session. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description The caller is not a candidate. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description The caller has no CV with that id. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description The request did not match the expected shape. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ValidationProblemDetail"];
                };
            };
            /** @description Something went wrong on the server. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description The stored file could not be reached. */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
}
