/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness check */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness check
         * @description Fails as a 500 problem+json if the database is unreachable.
         */
        get: operations["getReadiness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/signup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create a candidate account
         * @description Provision the identity, the Profile and the Candidate, and send a confirmation email.
         *
         *     No session comes back: the candidate has to confirm the address before they can sign in.
         *     Anything that fails part-way leaves the address free to sign up again.
         */
        post: operations["signUp"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/confirm-email": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Confirm an email address
         * @description Redeem the `token_hash` from the confirmation email, and sign the candidate in.
         *
         *     Signing them in is not a shortcut: redeeming the token proves they read mail sent to
         *     that address, which is the same thing a password proves about the account.
         */
        post: operations["confirmEmail"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/accept-invite": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Accept a teammate invitation
         * @description Redeem the `token_hash` from an invite email, choose a password, and sign in.
         *
         *     The Recruiter and their Tenant membership already exist — inviting is what created them
         *     — so this adds the one thing missing and drops the invitee straight into their team.
         */
        post: operations["acceptInvite"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start a session */
        post: operations["logIn"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Rotate the session
         * @description Exchange the refresh cookie for a new session, and replace both cookies with it.
         */
        post: operations["refreshSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * End the session
         * @description Revoke every session the caller has, then clear their cookies.
         *
         *     Succeeds whatever state the caller is in — a logout that could fail would be a way to
         *     leave someone signed in.
         */
        post: operations["logOut"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The signed-in Profile
         * @description Who the session cookie belongs to, once Supabase has verified its token.
         */
        get: operations["getCurrentProfile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/password-reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ask for a password-reset email
         * @description Send the reset email, if the address has an account.
         *
         *     Accepted either way, and with the same latency-free answer either way: a caller must not
         *     be able to learn from this endpoint whether an address is registered.
         */
        post: operations["requestPasswordReset"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/password-reset/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Set a new password
         * @description Redeem the `token_hash` from the reset email and set the new password.
         *
         *     Ends every session the account had, this caller's included, so the new password is the
         *     only way back in.
         */
        post: operations["confirmPasswordReset"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/tenants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create a tenant and its founding admin
         * @description Self-serve onto the platform: one call creates the Tenant and the admin who runs it.
         *
         *     No session comes back, exactly as for a candidate: the founder confirms their address
         *     first. Anything that fails part-way leaves neither a Tenant nor a usable address behind.
         */
        post: operations["signUpTenant"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/tenants/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The tenant the caller recruits for
         * @description Answers only while both kill-switches are off, which makes it the SPA's liveness check.
         */
        get: operations["getMyTenant"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/tenants/me/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The tenant's recruiters
         * @description Everyone on the roster, deactivated colleagues included — an admin has to see someone
         *     to reactivate them. Any recruiter may read it; only an admin may change it.
         */
        get: operations["listTenantMembers"];
        put?: never;
        /**
         * Invite a teammate
         * @description Mail an invitation and add the invitee to the roster in the same breath.
         *
         *     They are a member from this moment — 201 is not a promise, it is the row — but they
         *     cannot sign in until they follow the link and choose a password. An address that already
         *     belongs to anyone, Candidate or Recruiter, is refused: one address, one account.
         */
        post: operations["inviteTenantMember"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/tenants/me/members/{recruiter_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Change a teammate's role or access
         * @description Promote, demote, deactivate or reinstate a colleague.
         *
         *     Deactivating is how a departure is handled: the row and everything attached to it stays,
         *     and the person is refused at the door on their very next request.
         */
        patch: operations["changeTenantMember"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AcceptInviteRequest */
        AcceptInviteRequest: {
            /**
             * Token Hash
             * @description The `token_hash` from the emailed link.
             */
            token_hash: string;
            /**
             * Password
             * @description At least 8 characters.
             * @example correct-horse-battery
             */
            password: string;
        };
        /**
         * AccountType
         * @enum {string}
         */
        AccountType: "candidate" | "recruiter";
        /**
         * ChangeMemberRequest
         * @description Both fields optional: an admin changing a role should not have to restate access.
         */
        ChangeMemberRequest: {
            role?: components["schemas"]["RecruiterRole"] | null;
            /** Is Active */
            is_active?: boolean | null;
        };
        /** ConfirmEmailRequest */
        ConfirmEmailRequest: {
            /**
             * Token Hash
             * @description The `token_hash` from the emailed link.
             */
            token_hash: string;
        };
        /** ConfirmPasswordResetRequest */
        ConfirmPasswordResetRequest: {
            /**
             * Token Hash
             * @description The `token_hash` from the emailed link.
             */
            token_hash: string;
            /**
             * Password
             * @description At least 8 characters.
             * @example correct-horse-battery
             */
            password: string;
        };
        /**
         * Health
         * @description The process is up and serving.
         */
        Health: {
            /**
             * Status
             * @default ok
             * @constant
             */
            status: "ok";
        };
        /**
         * InvalidField
         * @description One rejected input, located by where it appeared in the request.
         */
        InvalidField: {
            /**
             * Location
             * @description Dotted path to the offending value, e.g. `body.email`.
             * @example body.email
             */
            location: string;
            /**
             * Message
             * @description Why the value was rejected.
             */
            message: string;
            /**
             * Type
             * @description Machine-readable validation rule that failed.
             */
            type: string;
        };
        /** InviteMemberRequest */
        InviteMemberRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Full Name */
            full_name: string;
            /** @default recruiter */
            role: components["schemas"]["RecruiterRole"];
        };
        /** LogInRequest */
        LogInRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /**
             * Password
             * @description At least 8 characters.
             * @example correct-horse-battery
             */
            password: string;
        };
        /**
         * MemberView
         * @description One Recruiter on the roster.
         */
        MemberView: {
            /**
             * Id
             * @description Shared with the Supabase Auth user and the Profile.
             */
            id: string;
            /** Full Name */
            full_name: string;
            /**
             * Email
             * Format: email
             */
            email: string;
            role: components["schemas"]["RecruiterRole"];
            /**
             * Is Active
             * @description False once an admin has revoked their access.
             */
            is_active: boolean;
        };
        /**
         * NewTenantView
         * @description What self-serve signup produced.
         */
        NewTenantView: {
            tenant: components["schemas"]["TenantView"];
            admin: components["schemas"]["MemberView"];
        };
        /** PasswordResetRequest */
        PasswordResetRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
        };
        /**
         * ProblemDetail
         * @description The body of any error response.
         */
        ProblemDetail: {
            /**
             * Type
             * @description Stable identifier for what went wrong.
             * @default about:blank
             * @example about:blank
             */
            type: string;
            /**
             * Title
             * @description Short, human-readable summary of the problem type.
             */
            title: string;
            /**
             * Status
             * @description The HTTP status code, repeated for out-of-band handling.
             */
            status: number;
            /**
             * Detail
             * @description Explanation specific to this occurrence.
             */
            detail?: string | null;
            /**
             * Instance
             * @description Path of the request that produced the problem.
             */
            instance?: string | null;
            /**
             * Request Id
             * @description Correlates this response with the server logs.
             */
            request_id?: string | null;
        } & {
            [key: string]: unknown;
        };
        /**
         * ProfileView
         * @description The acting Profile, as every auth route reports it.
         */
        ProfileView: {
            /**
             * Id
             * @description Shared with the Supabase Auth user and the Candidate row.
             */
            id: string;
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Full Name */
            full_name: string;
            account_type: components["schemas"]["AccountType"];
            /** Avatar Url */
            avatar_url: string | null;
            /** Phone */
            phone: string | null;
        };
        /**
         * Readiness
         * @description The process is up and its dependencies answer.
         */
        Readiness: {
            /**
             * Status
             * @default ok
             * @constant
             */
            status: "ok";
            /**
             * Database
             * @default ok
             * @constant
             */
            database: "ok";
        };
        /**
         * RecruiterRole
         * @enum {string}
         */
        RecruiterRole: "admin" | "recruiter";
        /** SignUpRequest */
        SignUpRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /**
             * Password
             * @description At least 8 characters.
             * @example correct-horse-battery
             */
            password: string;
            /** Full Name */
            full_name: string;
        };
        /** SignUpTenantRequest */
        SignUpTenantRequest: {
            /**
             * Tenant Name
             * @description The hiring company's display name.
             */
            tenant_name: string;
            /**
             * Slug
             * @description Lowercase letters, digits and single hyphens.
             * @example acme-recruiting
             */
            slug: string;
            /**
             * Email
             * Format: email
             * @description The founding admin's address.
             */
            email: string;
            /**
             * Password
             * @description At least 8 characters.
             * @example correct-horse-battery
             */
            password: string;
            /**
             * Full Name
             * @description The founding admin's name.
             */
            full_name: string;
        };
        /**
         * TenantView
         * @description A Tenant as its own recruiters see it.
         */
        TenantView: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Slug */
            slug: string;
        };
        /**
         * ValidationProblemDetail
         * @description A problem that can name every input it rejected.
         */
        ValidationProblemDetail: {
            /**
             * Type
             * @description Stable identifier for what went wrong.
             * @default about:blank
             * @example about:blank
             */
            type: string;
            /**
             * Title
             * @description Short, human-readable summary of the problem type.
             */
            title: string;
            /**
             * Status
             * @description The HTTP status code, repeated for out-of-band handling.
             */
            status: number;
            /**
             * Detail
             * @description Explanation specific to this occurrence.
             */
            detail?: string | null;
            /**
             * Instance
             * @description Path of the request that produced the problem.
             */
            instance?: string | null;
            /**
             * Request Id
             * @description Correlates this response with the server logs.
             */
            request_id?: string | null;
            /**
             * Errors
             * @description Every field that failed validation.
             */
            errors: components["schemas"]["InvalidField"][];
        } & {
            [key: string]: unknown;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
            /** @description The request did not match the expected shape. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ValidationProblemDetail"];
                };
            };
            /** @description Something went wrong on the server. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    getReadiness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Readiness"];
                };
            };
            /** @description The request did not match the expected shape. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ValidationProblemDetail"];
                };
            };
            /** @description Something went wrong on the server. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    signUp: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SignUpRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileView"];
                };
            };
            /** @description The identity provider rejected the password. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description An account already exists for this email address. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description The request did not match the expected shape. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ValidationProblemDetail"];
                };
            };
            /** @description Something went wrong on the server. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description The identity provider is not answering. */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    confirmEmail: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfirmEmailRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileView"];
                };
            };
            /** @description The link is invalid, spent, or expired. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description The request did not match the expected shape. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ValidationProblemDetail"];
                };
            };
            /** @description Something went wrong on the server. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description The identity provider is not answering. */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    acceptInvite: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AcceptInviteRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileView"];
                };
            };
            /** @description The link is spent or expired, or the password was refused. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description The request did not match the expected shape. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ValidationProblemDetail"];
                };
            };
            /** @description Something went wrong on the server. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description The identity provider is not answering. */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    logIn: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LogInRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileView"];
                };
            };
            /** @description The email and password do not match an account. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description The email address has not been confirmed yet. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description The request did not match the expected shape. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ValidationProblemDetail"];
                };
            };
            /** @description Something went wrong on the server. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description The identity provider is not answering. */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    refreshSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileView"];
                };
            };
            /** @description The session is over — sign in again. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description The request did not match the expected shape. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ValidationProblemDetail"];
                };
            };
            /** @description Something went wrong on the server. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description The identity provider is not answering. */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    logOut: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The request did not match the expected shape. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ValidationProblemDetail"];
                };
            };
            /** @description Something went wrong on the server. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    getCurrentProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileView"];
                };
            };
            /** @description There is no valid session. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description The request did not match the expected shape. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ValidationProblemDetail"];
                };
            };
            /** @description Something went wrong on the server. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    requestPasswordReset: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordResetRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The request did not match the expected shape. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ValidationProblemDetail"];
                };
            };
            /** @description Something went wrong on the server. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description The identity provider is not answering. */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    confirmPasswordReset: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfirmPasswordResetRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The link is spent or expired, or the password was refused. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description The request did not match the expected shape. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ValidationProblemDetail"];
                };
            };
            /** @description Something went wrong on the server. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description The identity provider is not answering. */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    signUpTenant: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SignUpTenantRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NewTenantView"];
                };
            };
            /** @description The identity provider rejected the password. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description The slug or the email address is already taken. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description The request did not match the expected shape. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ValidationProblemDetail"];
                };
            };
            /** @description Something went wrong on the server. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description The identity provider is not answering. */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    getMyTenant: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TenantView"];
                };
            };
            /** @description There is no valid session. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description The caller is not a recruiter, has been deactivated, or their tenant is suspended. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description The request did not match the expected shape. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ValidationProblemDetail"];
                };
            };
            /** @description Something went wrong on the server. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    listTenantMembers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberView"][];
                };
            };
            /** @description There is no valid session. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description The caller is not a recruiter, has been deactivated, or their tenant is suspended. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description The request did not match the expected shape. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ValidationProblemDetail"];
                };
            };
            /** @description Something went wrong on the server. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    inviteTenantMember: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InviteMemberRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberView"];
                };
            };
            /** @description There is no valid session. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description The caller is not a recruiter, has been deactivated, or their tenant is suspended. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description That email address already has a Sync account. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description The request did not match the expected shape. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ValidationProblemDetail"];
                };
            };
            /** @description Something went wrong on the server. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description The identity provider is not answering. */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    changeTenantMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                recruiter_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangeMemberRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberView"];
                };
            };
            /** @description There is no valid session. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description The caller is not a recruiter, has been deactivated, or their tenant is suspended. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description No such member of this tenant. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description The change would leave the tenant with no active admin. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description The request did not match the expected shape. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ValidationProblemDetail"];
                };
            };
            /** @description Something went wrong on the server. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
}
